sonar.projectKey=danarose22_8.2CDevSecOps
sonar.organization=danarose22
sonar.host.url=https://sonarcloud.io
sonar.login= 74adaa6729c7c2a9f72e3b9954f1e0a34b8845ef
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
